=== SvetlanaPaliashchuk/XMLParser/XMLParser/src/main/resources/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.jwd.com/orders"
        xmlns:tns="http://www.training.jwd.com/orders"
        elementFormDefault="qualified">
		
	<element name="orders">
        <complexType>
            <sequence>
                <element name="order" type="tns:order" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

	<complexType name="order">
        <sequence>
            <element name="city" type="string" minOccurs="1" maxOccurs="unbounded"/>
			<element name="startDate" type="tns:startDate" minOccurs="1" maxOccurs="1"/>
            <element name="duration" type="int" minOccurs="1" maxOccurs="1"/>
			<element name="numberOfTourists" type="int" minOccurs="1"/>
			<element name="tourists" type="tns:tourists" minOccurs="1"/>
            <element name="transport" type="tns:transport" minOccurs="1" />
            <element name="meal" type="tns:meal" minOccurs="0"/>
            <element name="price" type="double" minOccurs="1"/>
        </sequence>
            <attribute name="country" type="tns:country" use="required"/>
            <attribute name="tourType" type="tns:tourType" use="required"/>
            <attribute name="id" type="tns:id" use="required" />
    </complexType>
	
	
	<complexType name="tourists">
        <sequence>
			<element name="tourist" type="tns:tourist" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="tourist">
		<sequence>
            <element name="surname" type="string" maxOccurs="1"/>
			<element name="name" type="string" maxOccurs="1"/>
			<element name="passport" type="string" maxOccurs="1"/>
		</sequence>
	</complexType>
		
	<simpleType name="tourType">
        <restriction base="string">
            <enumeration value="vacation"/>
            <enumeration value="excursion"/>
            <enumeration value="weekend"/>
			<enumeration value="adventure"/>
			<enumeration value="shoping"/>
			<enumeration value="medical"/>
        </restriction>
    </simpleType>
    
    <simpleType name="country">
        <restriction base="string">
            <enumeration value="Bulgaria"/>
            <enumeration value="Turkey"/>
            <enumeration value="Thailand"/>
            <enumeration value="Egypt"/>
            <enumeration value="Spain"/>
            <enumeration value="Greece"/>
            <enumeration value="Ukraine"/>
            <enumeration value="China"/>
            <enumeration value="India"/>
            <enumeration value="Italy"/>
			<enumeration value="Lithuania"/>
        </restriction>
    </simpleType>
	
	 <simpleType name="id">
        <restriction base="ID">
            <pattern value="tv\d{1,7}"/>
        </restriction>
     </simpleType>
	
	<simpleType name="startDate">
        <restriction base="string">
            <pattern value="(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d"/>
        </restriction>
    </simpleType>
	
	 <simpleType name="transport">
        <restriction base="string">
            <enumeration value="car"/>
            <enumeration value="bus"/>
            <enumeration value="train"/>
            <enumeration value="airplane"/>
        </restriction>
    </simpleType>
	
	<simpleType name="meal">
        <restriction base="string">
            <enumeration value="AI"/>
            <enumeration value="BB"/>
            <enumeration value="HB"/>
            <enumeration value="FB"/>
			<enumeration value="RO"/>
			<enumeration value="UAI"/>
        </restriction>
    </simpleType>
	
</schema>

=== SvetlanaPaliashchuk/XMLParser/XMLParser/src/main/resources/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<orders xmlns="http://www.training.jwd.com/orders"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://www.training.jwd.com/orders orders.xsd">
			
	<order tourType="excursion" country="Lithuania" id="tv1">
		<city>Vilnius</city>
		<startDate>15.06.2020</startDate>
		<duration>2</duration>
		<numberOfTourists>1</numberOfTourists>
		<tourists>
			<tourist>
				<surname>Petrov</surname>
				<name>Aleksandr</name>
				<passport>DFO12345</passport>
			</tourist>
		</tourists>
		<transport>bus</transport>
		<meal>BB</meal>
		<price>90</price>
	</order>
	
    <order tourType="vacation" country="Spain" id="tv2">
        <city>Barcelona</city>
		<startDate>28/07/2020</startDate>
        <duration>7</duration>
        <numberOfTourists>2</numberOfTourists>
		<tourists>
			<tourist>
				<surname>Ivanov</surname>
				<name>Ivan</name>
				<passport>KSD12345</passport>
			</tourist>
			<tourist>
				<surname>Ivanova</surname>
				<name>Oksana</name>
				<passport>KSD12346</passport>
			</tourist>
		</tourists>
		<transport>airplane</transport>
		<meal>HB</meal>
        <price>1250</price>
    </order>
	
	<order tourType="weekend" country="Ukraine" id="tv3">
        <city>Kiev</city>
		<startDate>21/08/2020</startDate>
        <duration>3</duration>
        <numberOfTourists>2</numberOfTourists>
		<tourists>
			<tourist>
				<surname>Sidorova</surname>
				<name>Maria</name>
				<passport>GRE12345</passport>
			</tourist>
			<tourist>
				<surname>Timofeeva</surname>
				<name>Ekaterina</name>
				<passport>PGL12346</passport>
			</tourist>
		</tourists>
		<transport>train</transport>
		<meal>RO</meal>
        <price>500</price>
    </order>
	
	<order tourType="vacation" country="Egypt" id="tv4">
        <city>Sharm El Sheikh</city>
		<startDate>15/10/2020</startDate>
        <duration>12</duration>
        <numberOfTourists>3</numberOfTourists>
		<tourists>
			<tourist>
				<surname>Levkova</surname>
				<name>Anna</name>
				<passport>LED12345</passport>
			</tourist>
			<tourist>
				<surname>Levkov</surname>
				<name>Anton</name>
				<passport>LED12355</passport>
			</tourist>
			<tourist>
				<surname>Levkov</surname>
				<name>Egor</name>
				<passport>LED12255</passport>
			</tourist>
		</tourists>
		<transport>airplane</transport>
		<meal>AI</meal>
        <price>500</price>
    </order>
</orders>
